version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - pip3 install pytest
  pre_build:
    commands:
      - echo Authenticating with Amazon ECR…
      - aws ecr get-login-password --region $ECR_REGION | docker login --username AWS --password-stdin $ECR_REGISTRY_URI
  build:
    commands:
      - echo Running tests…
      - python -m pytest --junitxml=$REPORTS_FOLDER/$REPORTS_FILENAME tests
      - echo Building the Docker image…
      - docker build -t $PROJECT_NAME .
      - docker tag $PROJECT_NAME:latest $ECR_REGISTRY_URI/$PROJECT_NAME:latest
  post_build:
    commands:
      - echo Pushing the Docker image…
      - docker push $ECR_REGISTRY_URI/$PROJECT_NAME:latest
      - echo Updating Lambda image…
      - aws lambda update-function-code --function-name $LAMBDA_FUNCTION_NAME --image-uri $ECR_REGISTRY_URI/$PROJECT_NAME:latest
reports:
  pytest_reports:
    files:
      - $REPORTS_FILENAME
    base-directory: $REPORTS_FOLDER
    file-format: JUNITXML